name: Update Config.yaml

on:
  push:
    branches:
      - main

jobs:
  update-config:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Modify config.yaml
      run: |
        sed -i 's/^environment: prod$/environment: dev/' config.yaml

    - name: Push
      uses: s0/git-publish-subdir-action@develop
      env:
          REPO: self
          BRANCH: main
          FOLDER: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Changed dev to prod"