name: Update Config.yaml

on:
  push:
    branches:
      - main

jobs:
  update-config:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Modify config.yaml
      run: |
        sed -i 's/^environment: prod$/environment: dev/' config.yaml

    - name: Commit changes to config.yaml
      run: |
        git config --global user.name "AlfonsoJan"
        git config --global user.email "alfonsobusker@gmail.com"
        git add .
        git commit -m "Change environment from prod to dev"
        git push

    - name: Push
      uses: s0/git-publish-subdir-action@develop
      env:
          REPO: self
          BRANCH: main
          FOLDER: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Changed dev to prod"
