name: Update Config.yaml

on:
  push:
    branches:
      - main

jobs:
  update-config:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    outputs:
      config-changed: ${{ steps.check_changes.outcome }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug - Show config.yaml before modification
      run: cat config.yaml

    - name: Modify config.yaml
      run: |
        sed -i 's/environment: dev/environment: prod/' config.yaml

    - name: Debug - Show config.yaml after modification
      run: cat config.yaml

    - name: Check if config.yaml changed
      id: check_changes
      run: |
        # Check if there's a difference in config.yaml
        git diff --quiet config.yaml
        if [[ $? -eq 0 ]]; then
          echo "No changes detected in config.yaml"
          echo "config-changed=false" >> $GITHUB_ENV
        else
          echo "Changes detected in config.yaml"
          echo "config-changed=true" >> $GITHUB_ENV
        fi

    - name: Commit changes to config.yaml (if any)
      if: env.config-changed == 'true'
      run: |
        git config --global user.name "AlfonsoJan"
        git config --global user.email "alfonsobusker@gmail.com"
        git add config.yaml
        git status
        git commit -m "Change environment from dev to prod"
        git push

  build:
    runs-on: ubuntu-latest
    needs: update-config
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
