name: Update Config.yaml

on:
  push:
    branches:
      - main

jobs:
  update-config:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Modify config.yaml
      run: |
        sed -i 's/^\s*environment: dev\s*$/environment: prod/' config.yaml

    - name: Debug - Show config.yaml after modification
      run: cat config.yaml

    - name: Commit changes to config.yaml
      run: |
        git config --global user.name "AlfonsoJan"
        git config --global user.email "alfonsobusker@gmail.com"
        git add config.yaml
        git status
        git commit -m "Change environment from dev to prod"
        git push

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
